version: "3.9"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "7000:7000"
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"